// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, http, nonnon, os, path, _;

  express = require('express');

  path = require('path');

  http = require('http');

  os = require('os');

  _ = require('underscore');

  nonnon = require('./test.js');

  app = express();

  app.set("port", process.env.PORT || 3006);

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "dist")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", function(req, res) {
    return res.render('index');
  });

  app.get("/create", function(req, res) {
    var str;
    if (!req.query.string) {
      return res.send('error');
    }
    str = req.query.string;
    if (str.match(/^([^\x01-\x7E]{7})/)) {
      if (str.match(/^([^\x01-\x7E]{8})/)) {
        return res.send({
          result: 'error',
          msg: '日本語７文字制限あります'
        });
      }
      return nonnon.run(str, function(id) {
        return res.send({
          result: 'success',
          id: id
        });
      });
    } else {
      return res.send({
        result: 'error',
        msg: '日本語７文字制限あります'
      });
    }
  });

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("End-nanon listening on port " + app.get("port"));
  });

}).call(this);
